apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: strict-stack-selector
  title: Domain-Based Stack Selector with Repo Integration
  description: Select domain, focus area, and stack — then open matching GitHub repo in VSCode
spec:
  owner: user:your-username
  type: service

  parameters:
    - title: Select Your Domain and Area
      required: [domain, techArea]
      properties:
        domain:
          title: Domain
          type: string
          enum:
            - Insurance
            - Banking
            - HealthCare
            - Education
        techArea:
          title: Focus Area
          type: string
          enum:
            - Frontend
            - Backend
            - Database

      dependencies:
        domain:
          oneOf:

            # === Insurance Domain ===
            - properties:
                domain:
                  const: Insurance
                techArea:
                  enum: [Frontend, Backend, Database]
              required: [techArea]
              dependencies:
                techArea:
                  oneOf:
                    - properties:
                        techArea:
                          const: Frontend
                        frontend:
                          title: UI Framework
                          type: string
                          enum: [React]
                        repoUrl:
                          type: string
                          default: https://github.com/kjchandan/simple-frontend-code
                      required: [frontend]

                    - properties:
                        techArea:
                          const: Backend
                        backend:
                          title: Backend Platform
                          type: string
                          enum: [Django]
                        repoUrl:
                          type: string
                          default: https://github.com/your-org/insurance-django-backend
                      required: [backend]

                    - properties:
                        techArea:
                          const: Database
                        database:
                          title: Database
                          type: string
                          enum: [PostgreSQL]
                        repoUrl:
                          type: string
                          default: https://github.com/your-org/insurance-postgresql-schema
                      required: [database]

            # === Banking Domain ===
            - properties:
                domain:
                  const: Banking
                techArea:
                  enum: [Frontend, Backend, Database]
              required: [techArea]
              dependencies:
                techArea:
                  oneOf:
                    - properties:
                        techArea:
                          const: Frontend
                        frontend:
                          title: UI Framework
                          type: string
                          enum: [Vue.js]
                        repoUrl:
                          type: string
                          default: https://github.com/your-org/banking-vuejs-frontend
                      required: [frontend]

                    - properties:
                        techArea:
                          const: Backend
                        backend:
                          title: Backend Platform
                          type: string
                          enum: [Java]
                        repoUrl:
                          type: string
                          default: https://github.com/your-org/banking-java-backend
                      required: [backend]

                    - properties:
                        techArea:
                          const: Database
                        database:
                          title: Database
                          type: string
                          enum: [MySQL]
                        repoUrl:
                          type: string
                          default: https://github.com/your-org/banking-mysql-schema
                      required: [database]

            # === HealthCare Domain ===
            - properties:
                domain:
                  const: HealthCare
                techArea:
                  enum: [Frontend]
              required: [techArea]
              dependencies:
                techArea:
                  oneOf:
                    - properties:
                        techArea:
                          const: Frontend
                        frontend:
                          title: UI Framework
                          type: string
                          enum: [Angular 2+]
                        repoUrl:
                          type: string
                          default: https://github.com/your-org/healthcare-angular-frontend
                      required: [frontend]

            # === Education Domain ===
            - properties:
                domain:
                  const: Education
                techArea:
                  enum: [Backend]
              required: [techArea]
              dependencies:
                techArea:
                  oneOf:
                    - properties:
                        techArea:
                          const: Backend
                        backend:
                          title: Backend Platform
                          type: string
                          enum: [Springboot]
                        repoUrl:
                          type: string
                          default: https://github.com/your-org/education-springboot-backend
                      required: [backend]

  steps:
    - id: fetch
      name: Fetch Template Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          domain: ${{ parameters.domain }}
          techArea: ${{ parameters.techArea }}
          frontend: ${{ parameters.frontend }}
          backend: ${{ parameters.backend }}
          database: ${{ parameters.database }}

  output:
    text:
      - title: ✅ Project generated successfully
        content: |
          You selected:
          - Domain: ${{ parameters.domain }}
          - Focus Area: ${{ parameters.techArea }}
          - Frontend: ${{ parameters.frontend }}
          - Backend: ${{ parameters.backend }}
          - Database: ${{ parameters.database }}

    links:
      - title: 💻 Open in VSCode
        icon: code
        url: https://vscode.dev/${{ parameters.repoUrl | replace('https://github.com/', 'github.com/') }}

      - title: 🚀 Open in Replit
        icon: rocket
        url: https://replit.com/
