apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: single-tech-focus-stack
  title: Single Tech Focus Stack Template
  description: Choose domain and one tech area (frontend, backend, or database)
  tags:
    - generator
    - focused
    - frontend
    - backend
    - database

spec:
  owner: user:your-username
  type: service

  parameters:
    - title: Project Configuration
      required:
        - domain
        - techArea
      properties:
        domain:
          title: Select a Domain
          type: string
          enum:
            - Banking
            - Insurance
            - HealthCare
            - Education

        techArea:
          title: Focus Area
          type: string
          enum:
            - Frontend
            - Backend
            - Database

      dependencies:
        techArea:
          oneOf:
            # FRONTENDs
            - properties:
                techArea:
                  const: Frontend
                domain:
                  enum: [Banking]
                frontend:
                  title: UI Framework
                  type: string
                  enum: [Vue.js, Next.js, Typescript]
              required: [frontend]

            - properties:
                techArea:
                  const: Frontend
                domain:
                  enum: [Insurance]
                frontend:
                  title: UI Framework
                  type: string
                  enum: [React, Angular]
              required: [frontend]

            - properties:
                techArea:
                  const: Frontend
                domain:
                  enum: [HealthCare]
                frontend:
                  title: UI Framework
                  type: string
                  enum: [Three.js, ReactJs, Angular 2+]
              required: [frontend]

            - properties:
                techArea:
                  const: Frontend
                domain:
                  enum: [Education]
                frontend:
                  title: UI Framework
                  type: string
                  enum: [Vue.js, Next.js, Typescript, Three.js, ReactJs, Angular 2+]
              required: [frontend]

            # BACKENDs
            - properties:
                techArea:
                  const: Backend
                domain:
                  enum: [Banking]
                backend:
                  title: Backend Platform
                  type: string
                  enum: [Java, Python, Ruby]
              required: [backend]

            - properties:
                techArea:
                  const: Backend
                domain:
                  enum: [Insurance]
                backend:
                  title: Backend Platform
                  type: string
                  enum: [Scala, Go, Django]
              required: [backend]

            - properties:
                techArea:
                  const: Backend
                domain:
                  enum: [HealthCare]
                backend:
                  title: Backend Platform
                  type: string
                  enum: [Springboot, ASP.NET]
              required: [backend]

            - properties:
                techArea:
                  const: Backend
                domain:
                  enum: [Education]
                backend:
                  title: Backend Platform
                  type: string
                  enum:
                    - Java
                    - Python
                    - Ruby
                    - PHP Kotlin
                    - C sharp
                    - Perl
                    - Scala
                    - Go
                    - Djangi
                    - Springboot
                    - ASP.NET
              required: [backend]

            # DATABASEs
            - properties:
                techArea:
                  const: Database
                domain:
                  enum: [Banking, Insurance, HealthCare, Education]
                database:
                  title: Database
                  type: string
                  enum: [MYSQL, PostgreSQL]
              required: [database]

  steps:
    - id: fetch
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          domain: ${{ parameters.domain }}
          techArea: ${{ parameters.techArea }}
          frontend: ${{ parameters.frontend }}
          backend: ${{ parameters.backend }}
          database: ${{ parameters.database }}

  output:
    text:
      - title: ✅ Project Generated Successfully
        content: |
          You selected:
          - Domain: ${{ parameters.domain }}
          - Focus Area: ${{ parameters.techArea }}

          Stack:
          - Frontend: ${{ parameters.frontend }}
          - Backend: ${{ parameters.backend }}
          - Database: ${{ parameters.database }}

    links:
      - title: 💻 Open in VSCode
        icon: code
        url: https://vscode.dev/

      - title: 🚀 Open in Replit
        icon: rocket
        url: https://replit.com/
