apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: multi-step-stack-template
  title: Multi-Step Stack Selector
  description: Select domain and focus area, then choose appropriate tech stack in the next step
  tags:
    - wizard
    - frontend
    - backend
    - database

spec:
  owner: user:your-username
  type: service

  parameters:
    # Step 1 - Select domain and tech area
    - title: Project Info
      description: Choose your domain and tech focus.
      required:
        - domain
        - techArea
      properties:
        domain:
          title: Select a Domain
          type: string
          enum:
            - Banking
            - Insurance
            - HealthCare
            - Education
        techArea:
          title: Focus Area
          type: string
          enum:
            - Frontend
            - Backend
            - Database

    # Step 2 - Select tech stack based on techArea only
    - title: Tech Stack Selection
      description: Now select your technology stack based on the chosen focus area.
      dependencies:
        techArea:
          oneOf:
            - properties:
                techArea:
                  const: Frontend
                frontend:
                  title: UI Framework
                  type: string
                  enum:
                    - Vue.js (Banking, Education)
                    - Next.js (Banking, Education)
                    - Typescript (Banking, Education)
                    - React (Insurance)
                    - Angular (Insurance)
                    - Three.js (HealthCare, Education)
                    - ReactJs (HealthCare, Education)
                    - Angular 2+ (HealthCare, Education)
              required: [frontend]

            - properties:
                techArea:
                  const: Backend
                backend:
                  title: Backend Platform
                  type: string
                  enum:
                    - Java (Banking, Education)
                    - Python (Banking, Education)
                    - Ruby (Banking, Education)
                    - Scala (Insurance, Education)
                    - Go (Insurance, Education)
                    - Django (Insurance)
                    - Springboot (HealthCare, Education)
                    - ASP.NET (HealthCare, Education)
                    - PHP Kotlin (Education)
                    - C sharp (Education)
                    - Perl (Education)
                    - Djangi (Education)
              required: [backend]

            - properties:
                techArea:
                  const: Database
                database:
                  title: Database
                  type: string
                  enum:
                    - MYSQL
                    - PostgreSQL
              required: [database]

  steps:
    - id: fetch
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          domain: ${{ parameters.domain }}
          techArea: ${{ parameters.techArea }}
          frontend: ${{ parameters.frontend }}
          backend: ${{ parameters.backend }}
          database: ${{ parameters.database }}

  output:
    text:
      - title: ✅ Project Generated
        content: |
          You selected:
          - Domain: ${{ parameters.domain }}
          - Focus Area: ${{ parameters.techArea }}
          - Frontend: ${{ parameters.frontend }}
          - Backend: ${{ parameters.backend }}
          - Database: ${{ parameters.database }}

    links:
      - title: Open in VSCode
        icon: code
        url: https://vscode.dev/
