apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dynamic-tech-stack
  title: Dynamic Tech Stack Selector
  description: Choose domain and tech area, then get correct stack options
spec:
  owner: user:your-username
  type: service

  parameters:
    - title: Select Your Stack
      required: [domain, techArea]
      properties:
        domain:
          title: Domain
          type: string
          enum: [Banking, Insurance, HealthCare, Education]
        techArea:
          title: Focus Area
          type: string
          enum: [Frontend, Backend, Database]

      dependencies:
        domain:
          oneOf:
            # BANKING
            - properties:
                domain:
                  const: Banking
                techArea:
                  enum: [Frontend, Backend, Database]
              required: [techArea]
              dependencies:
                techArea:
                  oneOf:
                    - properties:
                        techArea:
                          const: Frontend
                        frontend:
                          title: UI Framework
                          type: string
                          enum: [Vue.js, Next.js, Typescript]
                      required: [frontend]
                    - properties:
                        techArea:
                          const: Backend
                        backend:
                          title: Backend Platform
                          type: string
                          enum: [Java, Python, Ruby]
                      required: [backend]
                    - properties:
                        techArea:
                          const: Database
                        database:
                          title: Database
                          type: string
                          enum: [MYSQL, PostgreSQL]
                      required: [database]

            # INSURANCE
            - properties:
                domain:
                  const: Insurance
                techArea:
                  enum: [Frontend, Backend, Database]
              required: [techArea]
              dependencies:
                techArea:
                  oneOf:
                    - properties:
                        techArea:
                          const: Frontend
                        frontend:
                          title: UI Framework
                          type: string
                          enum: [React, Angular]
                      required: [frontend]
                    - properties:
                        techArea:
                          const: Backend
                        backend:
                          title: Backend Platform
                          type: string
                          enum: [Scala, Go, Django]
                      required: [backend]
                    - properties:
                        techArea:
                          const: Database
                        database:
                          title: Database
                          type: string
                          enum: [MYSQL, PostgreSQL]
                      required: [database]

            # HEALTHCARE
            - properties:
                domain:
                  const: HealthCare
                techArea:
                  enum: [Frontend, Backend, Database]
              required: [techArea]
              dependencies:
                techArea:
                  oneOf:
                    - properties:
                        techArea:
                          const: Frontend
                        frontend:
                          title: UI Framework
                          type: string
                          enum: [Three.js, ReactJs, Angular 2+]
                      required: [frontend]
                    - properties:
                        techArea:
                          const: Backend
                        backend:
                          title: Backend Platform
                          type: string
                          enum: [Springboot, ASP.NET]
                      required: [backend]
                    - properties:
                        techArea:
                          const: Database
                        database:
                          title: Database
                          type: string
                          enum: [MYSQL, PostgreSQL]
                      required: [database]

            # EDUCATION
            - properties:
                domain:
                  const: Education
                techArea:
                  enum: [Frontend, Backend, Database]
              required: [techArea]
              dependencies:
                techArea:
                  oneOf:
                    - properties:
                        techArea:
                          const: Frontend
                        frontend:
                          title: UI Framework
                          type: string
                          enum: [Vue.js, Next.js, Typescript, Three.js, ReactJs, Angular 2+]
                      required: [frontend]
                    - properties:
                        techArea:
                          const: Backend
                        backend:
                          title: Backend Platform
                          type: string
                          enum:
                            - Java
                            - Python
                            - Ruby
                            - PHP Kotlin
                            - C sharp
                            - Perl
                            - Scala
                            - Go
                            - Djangi
                            - Springboot
                            - ASP.NET
                      required: [backend]
                    - properties:
                        techArea:
                          const: Database
                        database:
                          title: Database
                          type: string
                          enum: [MYSQL, PostgreSQL]
                      required: [database]

  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          domain: ${{ parameters.domain }}
          techArea: ${{ parameters.techArea }}
          frontend: ${{ parameters.frontend }}
          backend: ${{ parameters.backend }}
          database: ${{ parameters.database }}

  output:
    text:
      - title: ✅ Project generated successfully
        content: |
          You selected:
          - Domain: ${{ parameters.domain }}
          - Frontend: ${{ parameters.frontend }}
          - Backend: ${{ parameters.backend }}
          - Database: ${{ parameters.database }}

    links:
      - title: 💻 Open in VSCode (optional example)
        icon: code
        url: https://vscode.dev/

      - title: 🚀 Open in Replit (optional example)
        icon: rocket
        url: https://replit.com/
