apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: strict-stack-selector
  title: Strict Domain Tech Stack Selector with Repo Links
  description: Select domain, focus area, and tech stack → only the matching repo link shows
spec:
  owner: user:your-username
  type: service

  parameters:
    - title: Select Domain & Focus Area & Stack
      required: [domain, techArea]
      properties:
        domain:
          title: Domain
          type: string
          enum: [Banking, Insurance, HealthCare, Education]
        techArea:
          title: Focus Area
          type: string
          enum: [Frontend, Backend, Database]

      dependencies:
        domain:
          oneOf:

            # -------------------
            # Banking
            # -------------------
            - properties:
                domain:
                  const: Banking
                techArea:
                  enum: [Frontend, Backend, Database]
              required: [techArea]
              dependencies:
                techArea:
                  oneOf:
                    # Banking / Frontend
                    - properties:
                        techArea:
                          const: Frontend
                        frontend:
                          title: UI Framework
                          type: string
                          enum: [Vue.js, Next.js, Typescript]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/banking-vuejs-frontend
                            - https://github.com/your-org/banking-nextjs-frontend
                            - https://github.com/your-org/banking-typescript-frontend
                      required: [frontend]

                    # Banking / Backend
                    - properties:
                        techArea:
                          const: Backend
                        backend:
                          title: Backend Platform
                          type: string
                          enum: [Java, Python, Ruby]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/banking-java-backend
                            - https://github.com/your-org/banking-python-backend
                            - https://github.com/your-org/banking-ruby-backend
                      required: [backend]

                    # Banking / Database
                    - properties:
                        techArea:
                          const: Database
                        database:
                          title: Database
                          type: string
                          enum: [MYSQL, PostgreSQL]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/banking-mysql-schema
                            - https://github.com/your-org/banking-postgresql-schema
                      required: [database]

            # -------------------
            # Insurance
            # -------------------
            - properties:
                domain:
                  const: Insurance
                techArea:
                  enum: [Frontend, Backend, Database]
              required: [techArea]
              dependencies:
                techArea:
                  oneOf:
                    # Insurance / Frontend
                    - properties:
                        techArea:
                          const: Frontend
                        frontend:
                          title: UI Framework
                          type: string
                          enum: [React]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/kjchandan/simple-frontend-code
                      required: [frontend]

                    # Insurance / Backend
                    - properties:
                        techArea:
                          const: Backend
                        backend:
                          title: Backend Platform
                          type: string
                          enum: [Django]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/insurance-django-backend
                      required: [backend]

                    # Insurance / Database
                    - properties:
                        techArea:
                          const: Database
                        database:
                          title: Database
                          type: string
                          enum: [PostgreSQL]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/insurance-postgresql-schema
                      required: [database]

            # -------------------
            # HealthCare
            # -------------------
            - properties:
                domain:
                  const: HealthCare
                techArea:
                  enum: [Frontend, Backend, Database]
              required: [techArea]
              dependencies:
                techArea:
                  oneOf:
                    # HealthCare / Frontend
                    - properties:
                        techArea:
                          const: Frontend
                        frontend:
                          title: UI Framework
                          type: string
                          enum: [Angular 2+]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/healthcare-angular-frontend
                      required: [frontend]

                    # HealthCare / Backend
                    - properties:
                        techArea:
                          const: Backend
                        backend:
                          title: Backend Platform
                          type: string
                          enum: [Springboot]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/healthcare-springboot-backend
                      required: [backend]

                    # HealthCare / Database
                    - properties:
                        techArea:
                          const: Database
                        database:
                          title: Database
                          type: string
                          enum: [MYSQL]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/healthcare-mysql-schema
                      required: [database]

            # -------------------
            # Education
            # -------------------
            - properties:
                domain:
                  const: Education
                techArea:
                  enum: [Frontend, Backend, Database]
              required: [techArea]
              dependencies:
                techArea:
                  oneOf:
                    # Education / Frontend
                    - properties:
                        techArea:
                          const: Frontend
                        frontend:
                          title: UI Framework
                          type: string
                          enum: [ReactJs]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/education-reactjs-frontend
                      required: [frontend]

                    # Education / Backend
                    - properties:
                        techArea:
                          const: Backend
                        backend:
                          title: Backend Platform
                          type: string
                          enum: [Springboot]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/education-springboot-backend
                      required: [backend]

                    # Education / Database
                    - properties:
                        techArea:
                          const: Database
                        database:
                          title: Database
                          type: string
                          enum: [MYSQL, PostgreSQL]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/education-mysql-schema
                            - https://github.com/your-org/education-postgresql-schema
                      required: [database]

  steps:
    - id: fetch
      name: Fetch Template Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          domain: ${{ parameters.domain }}
          techArea: ${{ parameters.techArea }}
          frontend: ${{ parameters.frontend }}
          backend: ${{ parameters.backend }}
          database: ${{ parameters.database }}

  output:
    text:
      - title: ✅ Project generated successfully
        content: |
          You selected:
          - Domain: ${{ parameters.domain }}
          - Focus Area: ${{ parameters.techArea }}
          - Frontend: ${{ parameters.frontend }}
          - Backend: ${{ parameters.backend }}
          - Database: ${{ parameters.database }}

    links:
      - title: 💻 Open in VSCode
        icon: code
        url: https://vscode.dev/${{ parameters.repoUrl | replace('https://github.com/', 'github.com/') }}
