apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: strict-stack-selector
  title: Developer Friendly portal
  description: Provisioning Github repo codebase to VScode by selecting the techstack
  tags:
    - backstage
    - developer
    - techstack
    - technology
spec:
  owner: user:your-username
  type: service

  parameters:
    - title: Select Domain & Focus Area & Stack
      required: [domain, techArea]
      properties:
        domain:
          title: Domain
          type: string
          enum: [Banking, Insurance, HealthCare, Education]
        techArea:
          title: Focus Area
          type: string
          enum: [Frontend, Backend, Database]

      dependencies:
        domain:
          oneOf:
            # -------------------
            # Banking
            # -------------------
            - properties:
                domain:
                  const: Banking
                techArea:
                  enum: [Frontend, Backend, Database]
              required: [techArea]
              dependencies:
                techArea:
                  oneOf:
                    # Banking / Frontend
                    - properties:
                        techArea:
                          const: Frontend
                        frontend:
                          title: UI Framework
                          type: string
                          enum: [Vue.js, Next.js, Typescript]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/banking-vuejs-frontend
                            - https://github.com/your-org/banking-nextjs-frontend
                            - https://github.com/your-org/banking-typescript-frontend
                          ui:visibleIf: frontend  # Repo URL visible after selecting a frontend stack
                      # required: [frontend]

                    # Banking / Backend
                    - properties:
                        techArea:
                          const: Backend
                        backend:
                          title: Backend Platform
                          type: string
                          enum: [Java, Python, Ruby]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/banking-java-backend
                            - https://github.com/your-org/banking-python-backend
                            - https://github.com/your-org/banking-ruby-backend
                          ui:visibleIf: backend  # Repo URL visible after selecting a backend stack
                      required: [backend]

                    # Banking / Database
                    - properties:
                        techArea:
                          const: Database
                        database:
                          title: Database
                          type: string
                          enum: [MYSQL, PostgreSQL]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/banking-mysql-schema
                            - https://github.com/your-org/banking-postgresql-schema
                          ui:visibleIf: database  # Repo URL visible after selecting a database stack
                      required: [database]

            # -------------------
            # Insurance
            # -------------------
            - properties:
                domain:
                  const: Insurance
                techArea:
                  enum: [Frontend, Backend, Database]
              required: [techArea]
              dependencies:
                techArea:
                  oneOf:
                    # Insurance / Frontend
                    - properties:
                        techArea:
                          const: Frontend
                        frontend:
                          title: UI Framework
                          type: string
                          enum: [React, Angular]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/kjchandan/simple-frontend-code/tree/main
                            - https://github.com/your-org/insurance-angular-frontend
                          ui:visibleIf: frontend
                      required: [frontend]

                    # Insurance / Backend
                    - properties:
                        techArea:
                          const: Backend
                        backend:
                          title: Backend Platform
                          type: string
                          enum: [Scala, Go, Django]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/insurance-scala-backend
                            - https://github.com/your-org/insurance-go-backend
                            - https://github.com/your-org/insurance-django-backend
                          ui:visibleIf: backend
                      required: [backend]

                    # Insurance / Database
                    - properties:
                        techArea:
                          const: Database
                        database:
                          title: Database
                          type: string
                          enum: [MYSQL, PostgreSQL]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/insurance-mysql-schema
                            - https://github.com/your-org/insurance-postgresql-schema
                          ui:visibleIf: database
                      required: [database]

            # -------------------
            # HealthCare
            # -------------------
            - properties:
                domain:
                  const: HealthCare
                techArea:
                  enum: [Frontend, Backend, Database]
              required: [techArea]
              dependencies:
                techArea:
                  oneOf:
                    # HealthCare / Frontend
                    - properties:
                        techArea:
                          const: Frontend
                        frontend:
                          title: UI Framework
                          type: string
                          enum: [Three.js, ReactJs, Angular 2+]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/healthcare-threejs-frontend
                            - https://github.com/your-org/healthcare-reactjs-frontend
                            - https://github.com/your-org/healthcare-angular2-frontend
                          ui:visibleIf: frontend
                      required: [frontend]

                    # HealthCare / Backend
                    - properties:
                        techArea:
                          const: Backend
                        backend:
                          title: Backend Platform
                          type: string
                          enum: [Springboot, ASP.NET]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/healthcare-springboot-backend
                            - https://github.com/your-org/healthcare-aspnet-backend
                          ui:visibleIf: backend
                      required: [backend]

                    # HealthCare / Database
                    - properties:
                        techArea:
                          const: Database
                        database:
                          title: Database
                          type: string
                          enum: [MYSQL, PostgreSQL]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/healthcare-mysql-schema
                            - https://github.com/your-org/healthcare-postgresql-schema
                          ui:visibleIf: database
                      required: [database]

            # -------------------
            # Education
            # -------------------
            - properties:
                domain:
                  const: Education
                techArea:
                  enum: [Frontend, Backend, Database]
              required: [techArea]
              dependencies:
                techArea:
                  oneOf:
                    # Education / Frontend
                    - properties:
                        techArea:
                          const: Frontend
                        frontend:
                          title: UI Framework
                          type: string
                          enum: [Vue.js, Next.js, Typescript, Three.js, ReactJs, Angular 2+]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/education-vuejs-frontend
                            - https://github.com/your-org/education-nextjs-frontend
                            - https://github.com/your-org/education-typescript-frontend
                            - https://github.com/your-org/education-threejs-frontend
                            - https://github.com/your-org/education-reactjs-frontend
                            - https://github.com/your-org/education-angular2-frontend
                          ui:visibleIf: frontend
                      required: [frontend]

                    # Education / Backend
                    - properties:
                        techArea:
                          const: Backend
                        backend:
                          title: Backend Platform
                          type: string
                          enum: [Java, Python, Ruby, PHP, Kotlin, Csharp, Perl, Scala, Go, Django, Springboot, ASP.NET]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/education-java-backend
                            - https://github.com/your-org/education-python-backend
                            - https://github.com/your-org/education-ruby-backend
                            - https://github.com/your-org/education-php-backend
                            - https://github.com/your-org/education-kotlin-backend
                            - https://github.com/your-org/education-csharp-backend
                            - https://github.com/your-org/education-perl-backend
                            - https://github.com/your-org/education-scala-backend
                            - https://github.com/your-org/education-go-backend
                            - https://github.com/your-org/education-django-backend
                            - https://github.com/your-org/education-springboot-backend
                            - https://github.com/your-org/education-aspnet-backend
                          ui:visibleIf: backend
                      required: [backend]

                    # Education / Database
                    - properties:
                        techArea:
                          const: Database
                        database:
                          title: Database
                          type: string
                          enum: [MYSQL, PostgreSQL]
                        repoUrl:
                          title: Repo URL
                          type: string
                          enum:
                            - https://github.com/your-org/education-mysql-schema
                            - https://github.com/your-org/education-postgresql-schema
                          ui:visibleIf: database
                      required: [database]

  steps:
    - id: fetch
      name: Fetch Template Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          domain: ${{ parameters.domain }}
          techArea: ${{ parameters.techArea }}
          frontend: ${{ parameters.frontend }}
          backend: ${{ parameters.backend }}
          database: ${{ parameters.database }}

  output:
    text:
      - title: ✅ Project generated successfully
        content: |
          You selected:
          - Domain: ${{ parameters.domain }}
          - Focus Area: ${{ parameters.techArea }}
          - Frontend: ${{ parameters.frontend }}
          - Backend: ${{ parameters.backend }}
          - Database: ${{ parameters.database }}

    links:
      - title: 💻 Open in VSCode
        icon: code
        url: https://vscode.dev/${{ parameters.repoUrl | replace('https://github.com/', 'github.com/') }}
